#Name of the work flow
name: Release

#Run on every tag which begins with "v" (e.g, "v0.1.0")
on:
  push:
      tags:
          -"v"
#Atomatically create a Github Release, with release details specified (the relevant commits)
jobs:
    release:
        name: "Release"
        runs-on: "ubuntu-latest"
        steps:
            -uses: "marvininto/action-automatic-releases@latest"
            with:
                repo_token: "${{ secrets.GITHUB_TOKEN }}}"
                prerelease: false